AllCops:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'      
    - 'bin/**'
    - 'config/**/*'
    - 'lib/tasks/import_legacy.rake'
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 120

FrozenStringLiteralComment:
  Enabled: false

Style/ConditionalAssignment:
  EnforcedStyle: assign_to_condition

